version: '3'

services:
  # mysql
  mysql:
    image: mysql:5.7
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "6004:3306"
    volumes:
      - ./pkg/config/mysql:/etc/mysql/conf.d
      - ./pkg/data/mysql/:/var/lib/mysql/
      - ./pkg/data/init/:/docker-entrypoint-initdb.d/
      - ./pkg/log/mysql/:/var/log/mysql/
    command: [
        '--skip-name-resolve',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: always
  # redis
  redis:
    image: "library/redis:alpine"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6005:6379"
    volumes:
      - ./pkg/config/redis:/usr/local/etc/redis
      - ./pkg/data/redis/:/data/
      - ./pkg/log/redis/:/var/log/redis/
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
  # java
  boot:
    build:
      context: java/
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6007:4000"
    volumes:
      - ./pkg/log/springboot/:/log/
    depends_on:
      - mysql
      - redis
    restart: always
  # vue
  vue:
    build:
      context: vue/
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6060:80"
    volumes:
      - ./pkg/log/nginx/:/var/log/nginx/
    depends_on:
      - boot
    restart: always
  admin:
    build:
      context: admin/
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "3080:80"
    volumes:
      - ./pkg/log/admin/:/var/log/nginx/
    depends_on:
      - boot
    restart: always